create or replace table WIND(
	POSTAL_CODE VARCHAR(20),
	COUNTRY VARCHAR(2),
	DATE_VALID_STD DATE,
	MIN_WIND_SPEED_10M_MPS NUMBER(38,1),
	AVG_WIND_SPEED_10M_MPS NUMBER(38,1),
	MAX_WIND_SPEED_10M_MPS NUMBER(38,1)
);