CREATE TABLE FAKE_SOPHI3 (
    ACCOUNT_TYPE STRING,
    ACTIVE_TIME FLOAT,
    APP_ID STRING,
    ARTICLE_BYLINE STRING,
    ARTICLE_COLOUR STRING,
    COUNTRY STRING,
    DEVICE_BRAND STRING,
    DEVICE_TYPE STRING,
    EVENT_DATE_EST DATE,
    EVENT_NAME STRING,
    REGION STRING,
    SECTION STRING,
    TIMESTAMP_EST TIMESTAMP
);